<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML xmlns="http://www.w3.org/1999/xhtml"><HEAD><TITLE>MIME 参考手册</TITLE>
<META content="text/html; charset=gb2312" http-equiv=Content-Type>
<META content=zh-cn http-equiv=Content-Language>
<META name=robots content=all>
<META name=author content=w3school.com.cn>
<META name=Copyright content="Copyright W3school.com.cn All Rights Reserved.">
<META name=MSSmartTagsPreventParsing content=true>
<META content=false http-equiv=imagetoolbar><LINK rel=stylesheet type=text/css 
href="../c5.css"><LINK rel="shortcut icon" type=image/x-icon 
href="../favicon.ico">
<META name=GENERATOR content="MSHTML 10.00.9200.17267"></HEAD>
<BODY class=webbuilding>
<DIV id=wrapper>
<DIV id=header><A title="w3school 在线教程" style="FLOAT: left" 
href="../index.html">w3school 在线教程</A> 
<DIV id=ad_head>
<SCRIPT type=text/javascript><!--
google_ad_client = "pub-3381531532877742";
/* 728x90, 创建于 08-12-1 */
google_ad_slot = "7423315034";
google_ad_width = 728;
google_ad_height = 90;
//-->
</SCRIPT>
<ACRIPT src="../../pagead2.googlesyndication.com/pagead/show_ads.js" 
type="text/javascript"></SCRIPT></DIV></DIV>
<DIV id=navfirst>
<UL id=menu>
  <LI id=h><A title="HTML 系列教程" href="../h.asp">HTML 系列教程</A> </LI>
  <LI id=b><A title=浏览器脚本教程 href="../b.asp">浏览器脚本</A> </LI>
  <LI id=s><A title=服务器脚本教程 href="../s.asp">服务器脚本</A> </LI>
  <LI id=d><A title="ASP.NET 教程" href="../d.asp">ASP.NET 教程</A> </LI>
  <LI id=x><A title="XML 系列教程" href="../x.asp">XML 系列教程</A> </LI>
  <LI id=ws><A title="Web Services 系列教程" href="../ws.asp">Web Services 系列教程</A> 
  </LI>
  <LI id=w><A title=建站手册 href="../w.asp">建站手册</A> </LI></UL></DIV>
<DIV id=navsecond>
<DIV id=course>
<H2>Web 多媒体基础教程</H2>
<UL>
  <LI><A title="网络多媒体 教程" href="index.asp">媒体教程</A> 
  <LI><A title="Web 多媒体 简介" href="media_intro.asp">媒介简介</A> 
  <LI><A title="多媒体 音频格式" href="media_soundformats.asp">音频格式</A> 
  <LI><A title="多媒体 视频格式" href="media_videoformats.asp">视频格式</A> 
  <LI><A title="在 Web 上播放音频" href="media_browsersounds.asp">音频播放</A> 
  <LI><A title="在 Web 上播放视频" href="media_browservideos.asp">视频播放</A> 
  <LI><A title="Windows 多媒体格式" href="media_windowsformats.asp">视窗格式</A> </LI></UL>
<H2>图像基础教程</H2>
<UL>
  <LI><A title="多媒体教程 - GIF 图像" href="media_gif.asp">GIF 图像</A> 
  <LI><A title="多媒体教程 - JPEG 图像" href="media_jpeg.asp">JPEG 图像</A> 
  <LI><A title="多媒体教程 - 在 Web 上使用图像" href="media_browserimages.asp">使用图像</A> 
  </LI></UL>
<H2>Object 元素</H2>
<UL>
  <LI><A title="Object 元素" href="media_object.asp">Object 简介</A> 
  <LI><A title="播放 QuickTime 影片" href="media_quicktime.asp">Object QuickTime</A> 

  <LI><A title="播放 Real Video 影片" href="media_realvideo.asp">Object 
  RealVideo</A> </LI></UL>
<H2>参考手册</H2>
<UL>
  <LI><A title="Web 多媒体元素参考手册" href="media_tagref.asp">标签参考</A> 
  <LI><A title="Windows Media Player 参考手册" href="media_playerref.asp">播放器参考</A> 
  <LI class=currentLink><A title="MIME 参考手册" href="media_mimeref.asp">MIME 
  参考</A> </LI></UL></DIV>
<DIV id=selected>
<H2>建站手册</H2>
<UL>
  <LI><A title=网站构建 href="../site/index.asp">网站构建</A> 
  <LI><A title="万维网联盟 (W3C)" href="../w3c/index.asp">万维网联盟 (W3C)</A> 
  <LI><A title=浏览器信息 href="../browsers/index.asp">浏览器信息</A> 
  <LI><A title=网站品质 href="../quality/index.asp">网站品质</A> 
  <LI><A title=语义网 href="../semweb/index.asp">语义网</A> 
  <LI><A title=职业规划 href="../careers/index.asp">职业规划</A> 
  <LI><A title=网站主机 href="../hosting/index.asp">网站主机</A> </LI></UL>
<H2><A id=link_about title="关于 W3School" href="../about/index.asp">关于 
W3School</A></H2>
<H2><A id=link_help title="帮助 W3School" href="../about/about_helping.asp">帮助 
W3School</A></H2></DIV></DIV>
<DIV id=maincontent>
<H1>MIME 参考手册</H1>
<DIV id=tpn>
<UL class=prenext>
  <LI class=pre><A title="Windows Media Player 参考手册" 
  href="media_playerref.asp">播放器参考</A> </LI>
  <LI class=next><A title="网络多媒体 教程" href="index.asp">媒体教程</A> </LI></UL></DIV>
<DIV>
<H2>MIME 类型</H2>
<P>MIME (<EM>M</EM>ultipurpose <EM>I</EM>nternet <EM>M</EM>ail 
<EM>E</EM>xtensions) 是描述消息内容类型的因特网标准。</P>
<P>MIME 消息能包含文本、图像、音频、视频以及其他应用程序专用的数据。</P>
<P>官方的 MIME 信息是由 Internet Engineering Task Force (IETF) 在下面的文档中提供的：</P>
<UL>
  <LI><A title=rfc822 href="../../www.rfc-editor.org/rfc/rfc822.txt">RFC-822</A> 
  Standard for ARPA Internet text messages 
  <LI><A title=rfc2045 
  href="../../www.rfc-editor.org/rfc/rfc2045.txt">RFC-2045</A> MIME Part 1: 
  Format of Internet Message Bodies 
  <LI><A title=rfc2046 
  href="../../www.rfc-editor.org/rfc/rfc2046.txt">RFC-2046</A> MIME Part 2: 
  Media Types 
  <LI><A title=rfc2047 
  href="../../www.rfc-editor.org/rfc/rfc2047.txt">RFC-2047</A> MIME Part 3: 
  Header Extensions for Non-ASCII Text 
  <LI><A title=rfc2048 
  href="../../www.rfc-editor.org/rfc/rfc2048.txt">RFC-2048</A> MIME Part 4: 
  Registration Procedures 
  <LI><A title=rfc2049 
  href="../../www.rfc-editor.org/rfc/rfc2049.txt">RFC-2049</A> MIME Part 5: 
  Conformance Criteria and Examples </LI></UL>
<P>不同的应用程序支持不同的 MIME 类型。</P>
<P>下面的参考手册是由 Microsoft Internet Information Server version 5 所支持的 MIME 
类型列表。</P></DIV>
<DIV>
<H2>按照内容类型排列的 Mime 类型列表</H2>
<TABLE class=dataintable>
  <TBODY>
  <TR>
    <TH>类型/子类型</TH>
    <TH>扩展名</TH></TR>
  <TR>
    <TD>application/envoy</TD>
    <TD>evy</TD></TR>
  <TR>
    <TD>application/fractals</TD>
    <TD>fif</TD></TR>
  <TR>
    <TD>application/futuresplash</TD>
    <TD>spl</TD></TR>
  <TR>
    <TD>application/hta</TD>
    <TD>hta</TD></TR>
  <TR>
    <TD>application/internet-property-stream</TD>
    <TD>acx</TD></TR>
  <TR>
    <TD>application/mac-binhex40</TD>
    <TD>hqx</TD></TR>
  <TR>
    <TD>application/msword</TD>
    <TD>doc</TD></TR>
  <TR>
    <TD>application/msword</TD>
    <TD>dot</TD></TR>
  <TR>
    <TD>application/octet-stream</TD>
    <TD>*</TD></TR>
  <TR>
    <TD>application/octet-stream</TD>
    <TD>bin</TD></TR>
  <TR>
    <TD>application/octet-stream</TD>
    <TD>class</TD></TR>
  <TR>
    <TD>application/octet-stream</TD>
    <TD>dms</TD></TR>
  <TR>
    <TD>application/octet-stream</TD>
    <TD>exe</TD></TR>
  <TR>
    <TD>application/octet-stream</TD>
    <TD>lha</TD></TR>
  <TR>
    <TD>application/octet-stream</TD>
    <TD>lzh</TD></TR>
  <TR>
    <TD>application/oda</TD>
    <TD>oda</TD></TR>
  <TR>
    <TD>application/olescript</TD>
    <TD>axs</TD></TR>
  <TR>
    <TD>application/pdf</TD>
    <TD>pdf</TD></TR>
  <TR>
    <TD>application/pics-rules</TD>
    <TD>prf</TD></TR>
  <TR>
    <TD>application/pkcs10</TD>
    <TD>p10</TD></TR>
  <TR>
    <TD>application/pkix-crl</TD>
    <TD>crl</TD></TR>
  <TR>
    <TD>application/postscript</TD>
    <TD>ai</TD></TR>
  <TR>
    <TD>application/postscript</TD>
    <TD>eps</TD></TR>
  <TR>
    <TD>application/postscript</TD>
    <TD>ps</TD></TR>
  <TR>
    <TD>application/rtf</TD>
    <TD>rtf</TD></TR>
  <TR>
    <TD>application/set-payment-initiation</TD>
    <TD>setpay</TD></TR>
  <TR>
    <TD>application/set-registration-initiation</TD>
    <TD>setreg</TD></TR>
  <TR>
    <TD>application/vnd.ms-excel</TD>
    <TD>xla</TD></TR>
  <TR>
    <TD>application/vnd.ms-excel</TD>
    <TD>xlc</TD></TR>
  <TR>
    <TD>application/vnd.ms-excel</TD>
    <TD>xlm</TD></TR>
  <TR>
    <TD>application/vnd.ms-excel</TD>
    <TD>xls</TD></TR>
  <TR>
    <TD>application/vnd.ms-excel</TD>
    <TD>xlt</TD></TR>
  <TR>
    <TD>application/vnd.ms-excel</TD>
    <TD>xlw</TD></TR>
  <TR>
    <TD>application/vnd.ms-outlook</TD>
    <TD>msg</TD></TR>
  <TR>
    <TD>application/vnd.ms-pkicertstore</TD>
    <TD>sst</TD></TR>
  <TR>
    <TD>application/vnd.ms-pkiseccat</TD>
    <TD>cat</TD></TR>
  <TR>
    <TD>application/vnd.ms-pkistl</TD>
    <TD>stl</TD></TR>
  <TR>
    <TD>application/vnd.ms-powerpoint</TD>
    <TD>pot</TD></TR>
  <TR>
    <TD>application/vnd.ms-powerpoint</TD>
    <TD>pps</TD></TR>
  <TR>
    <TD>application/vnd.ms-powerpoint</TD>
    <TD>ppt</TD></TR>
  <TR>
    <TD>application/vnd.ms-project</TD>
    <TD>mpp</TD></TR>
  <TR>
    <TD>application/vnd.ms-works</TD>
    <TD>wcm</TD></TR>
  <TR>
    <TD>application/vnd.ms-works</TD>
    <TD>wdb</TD></TR>
  <TR>
    <TD>application/vnd.ms-works</TD>
    <TD>wks</TD></TR>
  <TR>
    <TD>application/vnd.ms-works</TD>
    <TD>wps</TD></TR>
  <TR>
    <TD>application/winhlp</TD>
    <TD>hlp</TD></TR>
  <TR>
    <TD>application/x-bcpio</TD>
    <TD>bcpio</TD></TR>
  <TR>
    <TD>application/x-cdf</TD>
    <TD>cdf</TD></TR>
  <TR>
    <TD>application/x-compress</TD>
    <TD>z</TD></TR>
  <TR>
    <TD>application/x-compressed</TD>
    <TD>tgz</TD></TR>
  <TR>
    <TD>application/x-cpio</TD>
    <TD>cpio</TD></TR>
  <TR>
    <TD>application/x-csh</TD>
    <TD>csh</TD></TR>
  <TR>
    <TD>application/x-director</TD>
    <TD>dcr</TD></TR>
  <TR>
    <TD>application/x-director</TD>
    <TD>dir</TD></TR>
  <TR>
    <TD>application/x-director</TD>
    <TD>dxr</TD></TR>
  <TR>
    <TD>application/x-dvi</TD>
    <TD>dvi</TD></TR>
  <TR>
    <TD>application/x-gtar</TD>
    <TD>gtar</TD></TR>
  <TR>
    <TD>application/x-gzip</TD>
    <TD>gz</TD></TR>
  <TR>
    <TD>application/x-hdf</TD>
    <TD>hdf</TD></TR>
  <TR>
    <TD>application/x-internet-signup</TD>
    <TD>ins</TD></TR>
  <TR>
    <TD>application/x-internet-signup</TD>
    <TD>isp</TD></TR>
  <TR>
    <TD>application/x-iphone</TD>
    <TD>iii</TD></TR>
  <TR>
    <TD>application/x-javascript</TD>
    <TD>js</TD></TR>
  <TR>
    <TD>application/x-latex</TD>
    <TD>latex</TD></TR>
  <TR>
    <TD>application/x-msaccess</TD>
    <TD>mdb</TD></TR>
  <TR>
    <TD>application/x-mscardfile</TD>
    <TD>crd</TD></TR>
  <TR>
    <TD>application/x-msclip</TD>
    <TD>clp</TD></TR>
  <TR>
    <TD>application/x-msdownload</TD>
    <TD>dll</TD></TR>
  <TR>
    <TD>application/x-msmediaview</TD>
    <TD>m13</TD></TR>
  <TR>
    <TD>application/x-msmediaview</TD>
    <TD>m14</TD></TR>
  <TR>
    <TD>application/x-msmediaview</TD>
    <TD>mvb</TD></TR>
  <TR>
    <TD>application/x-msmetafile</TD>
    <TD>wmf</TD></TR>
  <TR>
    <TD>application/x-msmoney</TD>
    <TD>mny</TD></TR>
  <TR>
    <TD>application/x-mspublisher</TD>
    <TD>pub</TD></TR>
  <TR>
    <TD>application/x-msschedule</TD>
    <TD>scd</TD></TR>
  <TR>
    <TD>application/x-msterminal</TD>
    <TD>trm</TD></TR>
  <TR>
    <TD>application/x-mswrite</TD>
    <TD>wri</TD></TR>
  <TR>
    <TD>application/x-netcdf</TD>
    <TD>cdf</TD></TR>
  <TR>
    <TD>application/x-netcdf</TD>
    <TD>nc</TD></TR>
  <TR>
    <TD>application/x-perfmon</TD>
    <TD>pma</TD></TR>
  <TR>
    <TD>application/x-perfmon</TD>
    <TD>pmc</TD></TR>
  <TR>
    <TD>application/x-perfmon</TD>
    <TD>pml</TD></TR>
  <TR>
    <TD>application/x-perfmon</TD>
    <TD>pmr</TD></TR>
  <TR>
    <TD>application/x-perfmon</TD>
    <TD>pmw</TD></TR>
  <TR>
    <TD>application/x-pkcs12</TD>
    <TD>p12</TD></TR>
  <TR>
    <TD>application/x-pkcs12</TD>
    <TD>pfx</TD></TR>
  <TR>
    <TD>application/x-pkcs7-certificates</TD>
    <TD>p7b</TD></TR>
  <TR>
    <TD>application/x-pkcs7-certificates</TD>
    <TD>spc</TD></TR>
  <TR>
    <TD>application/x-pkcs7-certreqresp</TD>
    <TD>p7r</TD></TR>
  <TR>
    <TD>application/x-pkcs7-mime</TD>
    <TD>p7c</TD></TR>
  <TR>
    <TD>application/x-pkcs7-mime</TD>
    <TD>p7m</TD></TR>
  <TR>
    <TD>application/x-pkcs7-signature</TD>
    <TD>p7s</TD></TR>
  <TR>
    <TD>application/x-sh</TD>
    <TD>sh</TD></TR>
  <TR>
    <TD>application/x-shar</TD>
    <TD>shar</TD></TR>
  <TR>
    <TD>application/x-shockwave-flash</TD>
    <TD>swf</TD></TR>
  <TR>
    <TD>application/x-stuffit</TD>
    <TD>sit</TD></TR>
  <TR>
    <TD>application/x-sv4cpio</TD>
    <TD>sv4cpio</TD></TR>
  <TR>
    <TD>application/x-sv4crc</TD>
    <TD>sv4crc</TD></TR>
  <TR>
    <TD>application/x-tar</TD>
    <TD>tar</TD></TR>
  <TR>
    <TD>application/x-tcl</TD>
    <TD>tcl</TD></TR>
  <TR>
    <TD>application/x-tex</TD>
    <TD>tex</TD></TR>
  <TR>
    <TD>application/x-texinfo</TD>
    <TD>texi</TD></TR>
  <TR>
    <TD>application/x-texinfo</TD>
    <TD>texinfo</TD></TR>
  <TR>
    <TD>application/x-troff</TD>
    <TD>roff</TD></TR>
  <TR>
    <TD>application/x-troff</TD>
    <TD>t</TD></TR>
  <TR>
    <TD>application/x-troff</TD>
    <TD>tr</TD></TR>
  <TR>
    <TD>application/x-troff-man</TD>
    <TD>man</TD></TR>
  <TR>
    <TD>application/x-troff-me</TD>
    <TD>me</TD></TR>
  <TR>
    <TD>application/x-troff-ms</TD>
    <TD>ms</TD></TR>
  <TR>
    <TD>application/x-ustar</TD>
    <TD>ustar</TD></TR>
  <TR>
    <TD>application/x-wais-source</TD>
    <TD>src</TD></TR>
  <TR>
    <TD>application/x-x509-ca-cert</TD>
    <TD>cer</TD></TR>
  <TR>
    <TD>application/x-x509-ca-cert</TD>
    <TD>crt</TD></TR>
  <TR>
    <TD>application/x-x509-ca-cert</TD>
    <TD>der</TD></TR>
  <TR>
    <TD>application/ynd.ms-pkipko</TD>
    <TD>pko</TD></TR>
  <TR>
    <TD>application/zip</TD>
    <TD>zip</TD></TR>
  <TR>
    <TD>audio/basic</TD>
    <TD>au</TD></TR>
  <TR>
    <TD>audio/basic</TD>
    <TD>snd</TD></TR>
  <TR>
    <TD>audio/mid</TD>
    <TD>mid</TD></TR>
  <TR>
    <TD>audio/mid</TD>
    <TD>rmi</TD></TR>
  <TR>
    <TD>audio/mpeg</TD>
    <TD>mp3</TD></TR>
  <TR>
    <TD>audio/x-aiff</TD>
    <TD>aif</TD></TR>
  <TR>
    <TD>audio/x-aiff</TD>
    <TD>aifc</TD></TR>
  <TR>
    <TD>audio/x-aiff</TD>
    <TD>aiff</TD></TR>
  <TR>
    <TD>audio/x-mpegurl</TD>
    <TD>m3u</TD></TR>
  <TR>
    <TD>audio/x-pn-realaudio</TD>
    <TD>ra</TD></TR>
  <TR>
    <TD>audio/x-pn-realaudio</TD>
    <TD>ram</TD></TR>
  <TR>
    <TD>audio/x-wav</TD>
    <TD>wav</TD></TR>
  <TR>
    <TD>image/bmp</TD>
    <TD>bmp</TD></TR>
  <TR>
    <TD>image/cis-cod</TD>
    <TD>cod</TD></TR>
  <TR>
    <TD>image/gif</TD>
    <TD>gif</TD></TR>
  <TR>
    <TD>image/ief</TD>
    <TD>ief</TD></TR>
  <TR>
    <TD>image/jpeg</TD>
    <TD>jpe</TD></TR>
  <TR>
    <TD>image/jpeg</TD>
    <TD>jpeg</TD></TR>
  <TR>
    <TD>image/jpeg</TD>
    <TD>jpg</TD></TR>
  <TR>
    <TD>image/pipeg</TD>
    <TD>jfif</TD></TR>
  <TR>
    <TD>image/svg+xml</TD>
    <TD>svg</TD></TR>
  <TR>
    <TD>image/tiff</TD>
    <TD>tif</TD></TR>
  <TR>
    <TD>image/tiff</TD>
    <TD>tiff</TD></TR>
  <TR>
    <TD>image/x-cmu-raster</TD>
    <TD>ras</TD></TR>
  <TR>
    <TD>image/x-cmx</TD>
    <TD>cmx</TD></TR>
  <TR>
    <TD>image/x-icon</TD>
    <TD>ico</TD></TR>
  <TR>
    <TD>image/x-portable-anymap</TD>
    <TD>pnm</TD></TR>
  <TR>
    <TD>image/x-portable-bitmap</TD>
    <TD>pbm</TD></TR>
  <TR>
    <TD>image/x-portable-graymap</TD>
    <TD>pgm</TD></TR>
  <TR>
    <TD>image/x-portable-pixmap</TD>
    <TD>ppm</TD></TR>
  <TR>
    <TD>image/x-rgb</TD>
    <TD>rgb</TD></TR>
  <TR>
    <TD>image/x-xbitmap</TD>
    <TD>xbm</TD></TR>
  <TR>
    <TD>image/x-xpixmap</TD>
    <TD>xpm</TD></TR>
  <TR>
    <TD>image/x-xwindowdump</TD>
    <TD>xwd</TD></TR>
  <TR>
    <TD>message/rfc822</TD>
    <TD>mht</TD></TR>
  <TR>
    <TD>message/rfc822</TD>
    <TD>mhtml</TD></TR>
  <TR>
    <TD>message/rfc822</TD>
    <TD>nws</TD></TR>
  <TR>
    <TD>text/css</TD>
    <TD>css</TD></TR>
  <TR>
    <TD>text/h323</TD>
    <TD>323</TD></TR>
  <TR>
    <TD>text/html</TD>
    <TD>htm</TD></TR>
  <TR>
    <TD>text/html</TD>
    <TD>html</TD></TR>
  <TR>
    <TD>text/html</TD>
    <TD>stm</TD></TR>
  <TR>
    <TD>text/iuls</TD>
    <TD>uls</TD></TR>
  <TR>
    <TD>text/plain</TD>
    <TD>bas</TD></TR>
  <TR>
    <TD>text/plain</TD>
    <TD>c</TD></TR>
  <TR>
    <TD>text/plain</TD>
    <TD>h</TD></TR>
  <TR>
    <TD>text/plain</TD>
    <TD>txt</TD></TR>
  <TR>
    <TD>text/richtext</TD>
    <TD>rtx</TD></TR>
  <TR>
    <TD>text/scriptlet</TD>
    <TD>sct</TD></TR>
  <TR>
    <TD>text/tab-separated-values</TD>
    <TD>tsv</TD></TR>
  <TR>
    <TD>text/webviewhtml</TD>
    <TD>htt</TD></TR>
  <TR>
    <TD>text/x-component</TD>
    <TD>htc</TD></TR>
  <TR>
    <TD>text/x-setext</TD>
    <TD>etx</TD></TR>
  <TR>
    <TD>text/x-vcard</TD>
    <TD>vcf</TD></TR>
  <TR>
    <TD>video/mpeg</TD>
    <TD>mp2</TD></TR>
  <TR>
    <TD>video/mpeg</TD>
    <TD>mpa</TD></TR>
  <TR>
    <TD>video/mpeg</TD>
    <TD>mpe</TD></TR>
  <TR>
    <TD>video/mpeg</TD>
    <TD>mpeg</TD></TR>
  <TR>
    <TD>video/mpeg</TD>
    <TD>mpg</TD></TR>
  <TR>
    <TD>video/mpeg</TD>
    <TD>mpv2</TD></TR>
  <TR>
    <TD>video/quicktime</TD>
    <TD>mov</TD></TR>
  <TR>
    <TD>video/quicktime</TD>
    <TD>qt</TD></TR>
  <TR>
    <TD>video/x-la-asf</TD>
    <TD>lsf</TD></TR>
  <TR>
    <TD>video/x-la-asf</TD>
    <TD>lsx</TD></TR>
  <TR>
    <TD>video/x-ms-asf</TD>
    <TD>asf</TD></TR>
  <TR>
    <TD>video/x-ms-asf</TD>
    <TD>asr</TD></TR>
  <TR>
    <TD>video/x-ms-asf</TD>
    <TD>asx</TD></TR>
  <TR>
    <TD>video/x-msvideo</TD>
    <TD>avi</TD></TR>
  <TR>
    <TD>video/x-sgi-movie</TD>
    <TD>movie</TD></TR>
  <TR>
    <TD>x-world/x-vrml</TD>
    <TD>flr</TD></TR>
  <TR>
    <TD>x-world/x-vrml</TD>
    <TD>vrml</TD></TR>
  <TR>
    <TD>x-world/x-vrml</TD>
    <TD>wrl</TD></TR>
  <TR>
    <TD>x-world/x-vrml</TD>
    <TD>wrz</TD></TR>
  <TR>
    <TD>x-world/x-vrml</TD>
    <TD>xaf</TD></TR>
  <TR>
    <TD>x-world/x-vrml</TD>
    <TD>xof</TD></TR></TBODY></TABLE></DIV>
<DIV>
<H2>按照文件扩展名排列的 Mime 类型列表</H2>
<TABLE class=dataintable>
  <TBODY>
  <TR>
    <TH>扩展名</TH>
    <TH>类型/子类型</TH></TR>
  <TR>
    <TD>&nbsp;</TD>
    <TD>application/octet-stream</TD></TR>
  <TR>
    <TD>323</TD>
    <TD>text/h323</TD></TR>
  <TR>
    <TD>acx</TD>
    <TD>application/internet-property-stream</TD></TR>
  <TR>
    <TD>ai</TD>
    <TD>application/postscript</TD></TR>
  <TR>
    <TD>aif</TD>
    <TD>audio/x-aiff</TD></TR>
  <TR>
    <TD>aifc</TD>
    <TD>audio/x-aiff</TD></TR>
  <TR>
    <TD>aiff</TD>
    <TD>audio/x-aiff</TD></TR>
  <TR>
    <TD>asf</TD>
    <TD>video/x-ms-asf</TD></TR>
  <TR>
    <TD>asr</TD>
    <TD>video/x-ms-asf</TD></TR>
  <TR>
    <TD>asx</TD>
    <TD>video/x-ms-asf</TD></TR>
  <TR>
    <TD>au</TD>
    <TD>audio/basic</TD></TR>
  <TR>
    <TD>avi</TD>
    <TD>video/x-msvideo</TD></TR>
  <TR>
    <TD>axs</TD>
    <TD>application/olescript</TD></TR>
  <TR>
    <TD>bas</TD>
    <TD>text/plain</TD></TR>
  <TR>
    <TD>bcpio</TD>
    <TD>application/x-bcpio</TD></TR>
  <TR>
    <TD>bin</TD>
    <TD>application/octet-stream</TD></TR>
  <TR>
    <TD>bmp</TD>
    <TD>image/bmp</TD></TR>
  <TR>
    <TD>c</TD>
    <TD>text/plain</TD></TR>
  <TR>
    <TD>cat</TD>
    <TD>application/vnd.ms-pkiseccat</TD></TR>
  <TR>
    <TD>cdf</TD>
    <TD>application/x-cdf</TD></TR>
  <TR>
    <TD>cer</TD>
    <TD>application/x-x509-ca-cert</TD></TR>
  <TR>
    <TD>class</TD>
    <TD>application/octet-stream</TD></TR>
  <TR>
    <TD>clp</TD>
    <TD>application/x-msclip</TD></TR>
  <TR>
    <TD>cmx</TD>
    <TD>image/x-cmx</TD></TR>
  <TR>
    <TD>cod</TD>
    <TD>image/cis-cod</TD></TR>
  <TR>
    <TD>cpio</TD>
    <TD>application/x-cpio</TD></TR>
  <TR>
    <TD>crd</TD>
    <TD>application/x-mscardfile</TD></TR>
  <TR>
    <TD>crl</TD>
    <TD>application/pkix-crl</TD></TR>
  <TR>
    <TD>crt</TD>
    <TD>application/x-x509-ca-cert</TD></TR>
  <TR>
    <TD>csh</TD>
    <TD>application/x-csh</TD></TR>
  <TR>
    <TD>css</TD>
    <TD>text/css</TD></TR>
  <TR>
    <TD>dcr</TD>
    <TD>application/x-director</TD></TR>
  <TR>
    <TD>der</TD>
    <TD>application/x-x509-ca-cert</TD></TR>
  <TR>
    <TD>dir</TD>
    <TD>application/x-director</TD></TR>
  <TR>
    <TD>dll</TD>
    <TD>application/x-msdownload</TD></TR>
  <TR>
    <TD>dms</TD>
    <TD>application/octet-stream</TD></TR>
  <TR>
    <TD>doc</TD>
    <TD>application/msword</TD></TR>
  <TR>
    <TD>dot</TD>
    <TD>application/msword</TD></TR>
  <TR>
    <TD>dvi</TD>
    <TD>application/x-dvi</TD></TR>
  <TR>
    <TD>dxr</TD>
    <TD>application/x-director</TD></TR>
  <TR>
    <TD>eps</TD>
    <TD>application/postscript</TD></TR>
  <TR>
    <TD>etx</TD>
    <TD>text/x-setext</TD></TR>
  <TR>
    <TD>evy</TD>
    <TD>application/envoy</TD></TR>
  <TR>
    <TD>exe</TD>
    <TD>application/octet-stream</TD></TR>
  <TR>
    <TD>fif</TD>
    <TD>application/fractals</TD></TR>
  <TR>
    <TD>flr</TD>
    <TD>x-world/x-vrml</TD></TR>
  <TR>
    <TD>gif</TD>
    <TD>image/gif</TD></TR>
  <TR>
    <TD>gtar</TD>
    <TD>application/x-gtar</TD></TR>
  <TR>
    <TD>gz</TD>
    <TD>application/x-gzip</TD></TR>
  <TR>
    <TD>h</TD>
    <TD>text/plain</TD></TR>
  <TR>
    <TD>hdf</TD>
    <TD>application/x-hdf</TD></TR>
  <TR>
    <TD>hlp</TD>
    <TD>application/winhlp</TD></TR>
  <TR>
    <TD>hqx</TD>
    <TD>application/mac-binhex40</TD></TR>
  <TR>
    <TD>hta</TD>
    <TD>application/hta</TD></TR>
  <TR>
    <TD>htc</TD>
    <TD>text/x-component</TD></TR>
  <TR>
    <TD>htm</TD>
    <TD>text/html</TD></TR>
  <TR>
    <TD>html</TD>
    <TD>text/html</TD></TR>
  <TR>
    <TD>htt</TD>
    <TD>text/webviewhtml</TD></TR>
  <TR>
    <TD>ico</TD>
    <TD>image/x-icon</TD></TR>
  <TR>
    <TD>ief</TD>
    <TD>image/ief</TD></TR>
  <TR>
    <TD>iii</TD>
    <TD>application/x-iphone</TD></TR>
  <TR>
    <TD>ins</TD>
    <TD>application/x-internet-signup</TD></TR>
  <TR>
    <TD>isp</TD>
    <TD>application/x-internet-signup</TD></TR>
  <TR>
    <TD>jfif</TD>
    <TD>image/pipeg</TD></TR>
  <TR>
    <TD>jpe</TD>
    <TD>image/jpeg</TD></TR>
  <TR>
    <TD>jpeg</TD>
    <TD>image/jpeg</TD></TR>
  <TR>
    <TD>jpg</TD>
    <TD>image/jpeg</TD></TR>
  <TR>
    <TD>js</TD>
    <TD>application/x-javascript</TD></TR>
  <TR>
    <TD>latex</TD>
    <TD>application/x-latex</TD></TR>
  <TR>
    <TD>lha</TD>
    <TD>application/octet-stream</TD></TR>
  <TR>
    <TD>lsf</TD>
    <TD>video/x-la-asf</TD></TR>
  <TR>
    <TD>lsx</TD>
    <TD>video/x-la-asf</TD></TR>
  <TR>
    <TD>lzh</TD>
    <TD>application/octet-stream</TD></TR>
  <TR>
    <TD>m13</TD>
    <TD>application/x-msmediaview</TD></TR>
  <TR>
    <TD>m14</TD>
    <TD>application/x-msmediaview</TD></TR>
  <TR>
    <TD>m3u</TD>
    <TD>audio/x-mpegurl</TD></TR>
  <TR>
    <TD>man</TD>
    <TD>application/x-troff-man</TD></TR>
  <TR>
    <TD>mdb</TD>
    <TD>application/x-msaccess</TD></TR>
  <TR>
    <TD>me</TD>
    <TD>application/x-troff-me</TD></TR>
  <TR>
    <TD>mht</TD>
    <TD>message/rfc822</TD></TR>
  <TR>
    <TD>mhtml</TD>
    <TD>message/rfc822</TD></TR>
  <TR>
    <TD>mid</TD>
    <TD>audio/mid</TD></TR>
  <TR>
    <TD>mny</TD>
    <TD>application/x-msmoney</TD></TR>
  <TR>
    <TD>mov</TD>
    <TD>video/quicktime</TD></TR>
  <TR>
    <TD>movie</TD>
    <TD>video/x-sgi-movie</TD></TR>
  <TR>
    <TD>mp2</TD>
    <TD>video/mpeg</TD></TR>
  <TR>
    <TD>mp3</TD>
    <TD>audio/mpeg</TD></TR>
  <TR>
    <TD>mpa</TD>
    <TD>video/mpeg</TD></TR>
  <TR>
    <TD>mpe</TD>
    <TD>video/mpeg</TD></TR>
  <TR>
    <TD>mpeg</TD>
    <TD>video/mpeg</TD></TR>
  <TR>
    <TD>mpg</TD>
    <TD>video/mpeg</TD></TR>
  <TR>
    <TD>mpp</TD>
    <TD>application/vnd.ms-project</TD></TR>
  <TR>
    <TD>mpv2</TD>
    <TD>video/mpeg</TD></TR>
  <TR>
    <TD>ms</TD>
    <TD>application/x-troff-ms</TD></TR>
  <TR>
    <TD>mvb</TD>
    <TD>application/x-msmediaview</TD></TR>
  <TR>
    <TD>nws</TD>
    <TD>message/rfc822</TD></TR>
  <TR>
    <TD>oda</TD>
    <TD>application/oda</TD></TR>
  <TR>
    <TD>p10</TD>
    <TD>application/pkcs10</TD></TR>
  <TR>
    <TD>p12</TD>
    <TD>application/x-pkcs12</TD></TR>
  <TR>
    <TD>p7b</TD>
    <TD>application/x-pkcs7-certificates</TD></TR>
  <TR>
    <TD>p7c</TD>
    <TD>application/x-pkcs7-mime</TD></TR>
  <TR>
    <TD>p7m</TD>
    <TD>application/x-pkcs7-mime</TD></TR>
  <TR>
    <TD>p7r</TD>
    <TD>application/x-pkcs7-certreqresp</TD></TR>
  <TR>
    <TD>p7s</TD>
    <TD>application/x-pkcs7-signature</TD></TR>
  <TR>
    <TD>pbm</TD>
    <TD>image/x-portable-bitmap</TD></TR>
  <TR>
    <TD>pdf</TD>
    <TD>application/pdf</TD></TR>
  <TR>
    <TD>pfx</TD>
    <TD>application/x-pkcs12</TD></TR>
  <TR>
    <TD>pgm</TD>
    <TD>image/x-portable-graymap</TD></TR>
  <TR>
    <TD>pko</TD>
    <TD>application/ynd.ms-pkipko</TD></TR>
  <TR>
    <TD>pma</TD>
    <TD>application/x-perfmon</TD></TR>
  <TR>
    <TD>pmc</TD>
    <TD>application/x-perfmon</TD></TR>
  <TR>
    <TD>pml</TD>
    <TD>application/x-perfmon</TD></TR>
  <TR>
    <TD>pmr</TD>
    <TD>application/x-perfmon</TD></TR>
  <TR>
    <TD>pmw</TD>
    <TD>application/x-perfmon</TD></TR>
  <TR>
    <TD>pnm</TD>
    <TD>image/x-portable-anymap</TD></TR>
  <TR>
    <TD>pot,</TD>
    <TD>application/vnd.ms-powerpoint</TD></TR>
  <TR>
    <TD>ppm</TD>
    <TD>image/x-portable-pixmap</TD></TR>
  <TR>
    <TD>pps</TD>
    <TD>application/vnd.ms-powerpoint</TD></TR>
  <TR>
    <TD>ppt</TD>
    <TD>application/vnd.ms-powerpoint</TD></TR>
  <TR>
    <TD>prf</TD>
    <TD>application/pics-rules</TD></TR>
  <TR>
    <TD>ps</TD>
    <TD>application/postscript</TD></TR>
  <TR>
    <TD>pub</TD>
    <TD>application/x-mspublisher</TD></TR>
  <TR>
    <TD>qt</TD>
    <TD>video/quicktime</TD></TR>
  <TR>
    <TD>ra</TD>
    <TD>audio/x-pn-realaudio</TD></TR>
  <TR>
    <TD>ram</TD>
    <TD>audio/x-pn-realaudio</TD></TR>
  <TR>
    <TD>ras</TD>
    <TD>image/x-cmu-raster</TD></TR>
  <TR>
    <TD>rgb</TD>
    <TD>image/x-rgb</TD></TR>
  <TR>
    <TD>rmi</TD>
    <TD>audio/mid</TD></TR>
  <TR>
    <TD>roff</TD>
    <TD>application/x-troff</TD></TR>
  <TR>
    <TD>rtf</TD>
    <TD>application/rtf</TD></TR>
  <TR>
    <TD>rtx</TD>
    <TD>text/richtext</TD></TR>
  <TR>
    <TD>scd</TD>
    <TD>application/x-msschedule</TD></TR>
  <TR>
    <TD>sct</TD>
    <TD>text/scriptlet</TD></TR>
  <TR>
    <TD>setpay</TD>
    <TD>application/set-payment-initiation</TD></TR>
  <TR>
    <TD>setreg</TD>
    <TD>application/set-registration-initiation</TD></TR>
  <TR>
    <TD>sh</TD>
    <TD>application/x-sh</TD></TR>
  <TR>
    <TD>shar</TD>
    <TD>application/x-shar</TD></TR>
  <TR>
    <TD>sit</TD>
    <TD>application/x-stuffit</TD></TR>
  <TR>
    <TD>snd</TD>
    <TD>audio/basic</TD></TR>
  <TR>
    <TD>spc</TD>
    <TD>application/x-pkcs7-certificates</TD></TR>
  <TR>
    <TD>spl</TD>
    <TD>application/futuresplash</TD></TR>
  <TR>
    <TD>src</TD>
    <TD>application/x-wais-source</TD></TR>
  <TR>
    <TD>sst</TD>
    <TD>application/vnd.ms-pkicertstore</TD></TR>
  <TR>
    <TD>stl</TD>
    <TD>application/vnd.ms-pkistl</TD></TR>
  <TR>
    <TD>stm</TD>
    <TD>text/html</TD></TR>
  <TR>
    <TD>svg</TD>
    <TD>image/svg+xml</TD></TR>
  <TR>
    <TD>sv4cpio</TD>
    <TD>application/x-sv4cpio</TD></TR>
  <TR>
    <TD>sv4crc</TD>
    <TD>application/x-sv4crc</TD></TR>
  <TR>
    <TD>swf</TD>
    <TD>application/x-shockwave-flash</TD></TR>
  <TR>
    <TD>t</TD>
    <TD>application/x-troff</TD></TR>
  <TR>
    <TD>tar</TD>
    <TD>application/x-tar</TD></TR>
  <TR>
    <TD>tcl</TD>
    <TD>application/x-tcl</TD></TR>
  <TR>
    <TD>tex</TD>
    <TD>application/x-tex</TD></TR>
  <TR>
    <TD>texi</TD>
    <TD>application/x-texinfo</TD></TR>
  <TR>
    <TD>texinfo</TD>
    <TD>application/x-texinfo</TD></TR>
  <TR>
    <TD>tgz</TD>
    <TD>application/x-compressed</TD></TR>
  <TR>
    <TD>tif</TD>
    <TD>image/tiff</TD></TR>
  <TR>
    <TD>tiff</TD>
    <TD>image/tiff</TD></TR>
  <TR>
    <TD>tr</TD>
    <TD>application/x-troff</TD></TR>
  <TR>
    <TD>trm</TD>
    <TD>application/x-msterminal</TD></TR>
  <TR>
    <TD>tsv</TD>
    <TD>text/tab-separated-values</TD></TR>
  <TR>
    <TD>txt</TD>
    <TD>text/plain</TD></TR>
  <TR>
    <TD>uls</TD>
    <TD>text/iuls</TD></TR>
  <TR>
    <TD>ustar</TD>
    <TD>application/x-ustar</TD></TR>
  <TR>
    <TD>vcf</TD>
    <TD>text/x-vcard</TD></TR>
  <TR>
    <TD>vrml</TD>
    <TD>x-world/x-vrml</TD></TR>
  <TR>
    <TD>wav</TD>
    <TD>audio/x-wav</TD></TR>
  <TR>
    <TD>wcm</TD>
    <TD>application/vnd.ms-works</TD></TR>
  <TR>
    <TD>wdb</TD>
    <TD>application/vnd.ms-works</TD></TR>
  <TR>
    <TD>wks</TD>
    <TD>application/vnd.ms-works</TD></TR>
  <TR>
    <TD>wmf</TD>
    <TD>application/x-msmetafile</TD></TR>
  <TR>
    <TD>wps</TD>
    <TD>application/vnd.ms-works</TD></TR>
  <TR>
    <TD>wri</TD>
    <TD>application/x-mswrite</TD></TR>
  <TR>
    <TD>wrl</TD>
    <TD>x-world/x-vrml</TD></TR>
  <TR>
    <TD>wrz</TD>
    <TD>x-world/x-vrml</TD></TR>
  <TR>
    <TD>xaf</TD>
    <TD>x-world/x-vrml</TD></TR>
  <TR>
    <TD>xbm</TD>
    <TD>image/x-xbitmap</TD></TR>
  <TR>
    <TD>xla</TD>
    <TD>application/vnd.ms-excel</TD></TR>
  <TR>
    <TD>xlc</TD>
    <TD>application/vnd.ms-excel</TD></TR>
  <TR>
    <TD>xlm</TD>
    <TD>application/vnd.ms-excel</TD></TR>
  <TR>
    <TD>xls</TD>
    <TD>application/vnd.ms-excel</TD></TR>
  <TR>
    <TD>xlt</TD>
    <TD>application/vnd.ms-excel</TD></TR>
  <TR>
    <TD>xlw</TD>
    <TD>application/vnd.ms-excel</TD></TR>
  <TR>
    <TD>xof</TD>
    <TD>x-world/x-vrml</TD></TR>
  <TR>
    <TD>xpm</TD>
    <TD>image/x-xpixmap</TD></TR>
  <TR>
    <TD>xwd</TD>
    <TD>image/x-xwindowdump</TD></TR>
  <TR>
    <TD>z</TD>
    <TD>application/x-compress</TD></TR>
  <TR>
    <TD>zip</TD>
    <TD>application/zip</TD></TR></TBODY></TABLE></DIV>
<DIV id=bpn>
<UL class=prenext>
  <LI class=pre><A title="Windows Media Player 参考手册" 
  href="media_playerref.asp">播放器参考</A> </LI>
  <LI class=next><A title="网络多媒体 教程" href="index.asp">媒体教程</A> 
</LI></UL></DIV></DIV>
<DIV id=sidebar>
<DIV id=searchui>
<FORM id=searchform method=get action=http://www.google.com.hk/search>
<P><LABEL for=searched_content>Search:</LABEL></P>
<P><INPUT type=hidden value=w3school.com.cn name=sitesearch></P>
<P><INPUT id=searched_content title=在此输入搜索内容。 class=box name=as_q> <INPUT title=搜索！ class=button type=submit value=Go> </P></FORM></DIV>
<DIV id=tools>
<H5 id=tools_reference><A href="media_tagref.asp">Web 多媒体元素参考手册</A></H5></DIV>
<DIV id=ad>
<SCRIPT type=text/javascript><!--
google_ad_client = "ca-pub-3381531532877742";
/* sidebar-160x600 */
google_ad_slot = "3772569310";
google_ad_width = 160;
google_ad_height = 600;
//-->
</SCRIPT>
<ACRIPT src="../../pagead2.googlesyndication.com/pagead/show_ads.js" 
type="text/javascript"></SCRIPT></DIV></DIV>
<DIV id=footer>
<P>W3School 提供的内容仅用于培训。我们不保证内容的正确性。通过使用本站内容随之而来的风险与本站无关。W3School 
简体中文版的所有内容仅供测试，对任何法律问题及风险不承担任何责任。 </P>
<P>当使用本站时，代表您已接受了本站的<A title=关于使用 href="../about/about_use.asp">使用条款</A>和<A 
title=关于隐私 href="../about/about_privacy.asp">隐私条款</A>。版权所有，保留一切权利。赞助商：<A 
title=上海赢科投资有限公司 href="../../www.yktz.net/default.htm">上海赢科投资有限公司</A>。 <A 
href="../../www.miitbeian.gov.cn/default.htm">蒙ICP备06004630号</A> 
</P></DIV></DIV></BODY></HTML>
